version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11

    working_directory: /go/src/github.com/stefanoj3/samsungremote
    steps:
      - checkout

      - run: make vendor
      - run: make test